# Generated by Django 5.2.6 on 2026-09-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
